name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respo
        uses: actions/checkout@v3
      
      - name: Setup builder
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - run: docker buildx create --name builder --driver docker-container --platform linux/amd64,linux/arm64 --use
      - run: docker buildx inspect --bootstrap

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push(Python 3.9)
        run: docker buildx build -t moefaq/v2board_telegram_bot:py3.9 -t moefaq/v2board_telegram_bot:latest --platform linux/amd64,linux/arm64 --progress plain --push -f Dockerized/py3.9/Dockerfile .

      - name: Build image and push(Python 3.10)
        run: docker buildx build -t moefaq/v2board_telegram_bot:py3.10 --platform linux/amd64,linux/arm64 --progress plain --push -f Dockerized/py3.10/Dockerfile .

      - name: Build image and push(Python 3.11)
        run: docker buildx build -t moefaq/v2board_telegram_bot:py3.11 --platform linux/amd64,linux/arm64 --progress plain --push -f Dockerized/py3.11/Dockerfile .
